version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: my_express_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - REDIS_URI=${REDIS_URI}
      - NODE_ENV=development
      - JWT_SECRET=LifeLineITMadeByEttisafRup
      - EMAIL_ADDRESS=xtendverify@gmail.com
      - EMAIL_PASSWORD=igvgyrkbdaqqsxdc
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
